지난 차시 : MSE 계산

In [1]:
import pandas as pd 
import numpy as np 

dataset/dataset/abalone.csv

### 범주형 데이터를 수치형 데이터로 변환
1. Sex가 문자열로 되어있으므로 계산하기 어렵다.
    - 해결방법 : 수로 변환한다.
        - 열을 지운다? : 데이터는 최대한 보존하는 것이 좋다.
        - F, M, I를 각각 1, 2, 3으로 변환한다? : 선형성의 문제. 수가 의미하는 바와 해당 라벨이 의미하는 바가 일치하지 않으므로 불가.
        - one hot vector : 초창기 자연어 처리에서 사용

### One - hot Vector

<!-- <img src =img/OneHotVector.png alt="one hot vector" width = 300> -->

![one hot vector](img/OneHotVector.png)

- 단점 : 희소행렬, 희소벡터가 만들어지며 데이터가 의미하는 바에 대해 데이터가 차지하는 크기가 커진다. (자연어처리에서 보충)

### One hot Encoding Practice

변수화

rows = ['I', 0.455, 0.365, 0.095] = [0,0,1, 0.455, 0.365, 0.095]

In [2]:
rows = ['I', 0.455, 0.365, 0.095] 
rows = ['M', 0.455, 0.365, 0.095] 
rows = ['F', 0.455, 0.365, 0.095] 

import numpy as np

data = np.zeros(6)      # 앞에 세개만 Sex 열이고 나머지는 그대로 (length ...)
print(data)

[0. 0. 0. 0. 0. 0.]


In [3]:
if rows[0] == 'M':
    data[0] = 1 
elif rows[0] == 'F':
    data[1] = 1
elif rows[0] == 'I':
    data[2] = 1

print(data)

[0. 1. 0. 0. 0. 0.]


In [4]:
print(rows)
print("================")
print("================")
print(data)

['F', 0.455, 0.365, 0.095]
[0. 1. 0. 0. 0. 0.]


In [5]:
# one hot encoding 한 data 와 나머지 데이터 rows를 합한다

data[3:] = rows[1:]
print(data)

[0.    1.    0.    0.455 0.365 0.095]


## dataset/dataset/abalone_mini

1. 데이터를 불러오기
    1. pandas : pd.resd_csv
    2. csv library

2. 가장 앞의 행을 세개로 분할한다.

In [6]:
import csv

In [7]:
# 데이터를 여는 것과 읽는 것은 다른 개념

with open('dataset/dataset/abalone_mini.csv') as csvfile:   # 열기
    csvreader = csv.reader(csvfile)     # 읽기

    # 반복문으로 데이터를 실제 변수에 할당
    rows = []
    for row in csvreader:
        rows.append(row)


In [8]:
rows

[['M', '0.455', '0.365', '0.095', '0.514', '0.2245', '0.101', '0.15', '15'],
 ['M', '0.35', '0.265', '0.09', '0.2255', '0.0995', '0.0485', '0.07', '7'],
 ['F', '0.53', '0.42', '0.135', '0.677', '0.2565', '0.1415', '0.21', '9'],
 ['M', '0.44', '0.365', '0.125', '0.516', '0.2155', '0.114', '0.155', '10'],
 ['I', '0.33', '0.255', '0.08', '0.205', '0.0895', '0.0395', '0.055', '7']]

In [9]:
# hint : zeros, enumerate

abalone_mini_buffer = np.zeros((len(rows), 2+len(rows[0])))
# abalone_mini_buffer.shape   (5, 11)

for idx, row in enumerate(rows):
    # one hot vector
    if row[0] == 'M': abalone_mini_buffer[idx][0] = 1
    elif row[0] == 'F': abalone_mini_buffer[idx][1] = 1
    elif row[0] == 'I': abalone_mini_buffer[idx][2] = 1

    # 남은 데이터 병합
    abalone_mini_buffer[idx][3:] = row[1:]

abalone_mini_buffer


array([[ 1.    ,  0.    ,  0.    ,  0.455 ,  0.365 ,  0.095 ,  0.514 ,
         0.2245,  0.101 ,  0.15  , 15.    ],
       [ 1.    ,  0.    ,  0.    ,  0.35  ,  0.265 ,  0.09  ,  0.2255,
         0.0995,  0.0485,  0.07  ,  7.    ],
       [ 0.    ,  1.    ,  0.    ,  0.53  ,  0.42  ,  0.135 ,  0.677 ,
         0.2565,  0.1415,  0.21  ,  9.    ],
       [ 1.    ,  0.    ,  0.    ,  0.44  ,  0.365 ,  0.125 ,  0.516 ,
         0.2155,  0.114 ,  0.155 , 10.    ],
       [ 0.    ,  0.    ,  1.    ,  0.33  ,  0.255 ,  0.08  ,  0.205 ,
         0.0895,  0.0395,  0.055 ,  7.    ]])

### 신경망을 동작할 때 가장 중요한 것?

weight, bias
- weight : 입력값의 개수만큼 필요  
- bias : 연산횟수만큼 필요

### 함수 안에 함수 작성하기?

위 방법처럼 메인 함수 안에 다른 함수를 실행시켜 모든 프로세스를 한번에 동작시킨다.

In [10]:
RND_MEAN, RND_STD = 0, 1
input_cnt, output_cnt = 10, 1


def import_data():
    pass 

def model_init():
    global weight, bias     # 전역변수 선언
    # 가중치 / 편향
    # 파라미터 -> 무작위 값으로 설정
    weight = np.random.normal(RND_MEAN, RND_STD, size = [input_cnt, output_cnt])     # np.random.normal : 평균, 표준편차, 개수
    bias = np.random.normal(RND_MEAN, RND_STD, size = output_cnt)   # 개수가 output_cnt임에 유의

# 순전파 구현 실습
# 구해야 할 것 : y_hat = (x * weight) + bias 
def train_and_test(x):  # x는 one hot encoding한 `data`의 처음부터 종속변수 전까지만 [:-1] 대입한다.
    y_hat = np.matmul(x, weight) + bias
    return y_hat



def main_exec(x):    # main function
    import_data()   # func1
    model_init()    # func2
    train_and_test(x)    # func3

# exec : y_pred
y_pred = main_exec(abalone_mini_buffer[:, :-1])
print(y_pred)

# exec : weight, bias
print(f'weight\n{weight}')
print(f'bias : {bias}')

None
weight
[[-0.58585203]
 [-1.55170218]
 [ 0.96004485]
 [-1.11185307]
 [-1.42163792]
 [-0.22569849]
 [ 0.8942494 ]
 [ 1.08493933]
 [-0.33764268]
 [ 1.61818724]]
bias : [2.05085196]


### 외부 함수를 클래스로 연동시켜 쓰는 방법

In [11]:
class Test():
    def __init__(self, x):
        self.x = x 

In [19]:
def main_exec(x):
    import_data()
    model_init()
    train_and_test(x)

Test.C_main_exec = main_exec
Test.CCCC_main_exec = main_exec

x = abalone_mini_buffer[:, :-1]
Test.C_main_exec(x)
Test.CCCC_main_exec(x)


None


### `.ipynb` 를 외부 모듈로 불러오기

불러온다기 보다는 한 줄로 실행시키는 개념

In [20]:
 # 실행시키는 것이므로 intro에서 만들었던 모델이 학습된다. 실행시간이 오래 걸리므로 주석처리
# %run 01_intro.ipynb  

[[ 1.49833384]
 [-1.09770039]
 [-0.42184873]]
[-0.95457998]
[[-0.71357435]
 [-0.75902012]]
예측 값
y hat total[0] : [-0.71357435]
y hat total[1] : [-0.75902012]
실제 y값 : [[15], [7]]
MSE : [153.55940602]
Epoch 1/1000
1/1 [==============================] - 0s 0s/step - loss: 0.2622
Epoch 2/1000
1/1 [==============================] - 0s 990us/step - loss: 0.2614
Epoch 3/1000
1/1 [==============================] - 0s 998us/step - loss: 0.2606
Epoch 4/1000
1/1 [==============================] - 0s 0s/step - loss: 0.2598
Epoch 5/1000
1/1 [==============================] - 0s 0s/step - loss: 0.2591
Epoch 6/1000
1/1 [==============================] - 0s 997us/step - loss: 0.2584
Epoch 7/1000
1/1 [==============================] - 0s 0s/step - loss: 0.2577
Epoch 8/1000
1/1 [==============================] - 0s 0s/step - loss: 0.2570
Epoch 9/1000
1/1 [==============================] - 0s 0s/step - loss: 0.2563
Epoch 10/1000
1/1 [==============================] - 0s 998us/step - loss: 0.2557
Epoch 11