In [1]:
# Array 는 정적(수동적) 할당이고, List 는 동적(능동적) 할당임을 잊지 마세요.
# 즉, Array 는 고정된 크기를 갖지만, List 는 계속 크기가 변할 수 있습니다.
# 넘파이는 많은 데이터를 다루고 계산할 수 있는 라이브러리 입니다.

# 넘파이 선언
import numpy as np

print( "--1차원 배열 선언 + 데이터 타입 변경------------" )
array_1d = np.array([8, 2, 2, 5, 9, 10, 13, 3], dtype=float)
print( array_1d )
print( "-----------------------------------------" )

print( "--2차원 배열 선언 + 데이터 타입 변경------------" )
array_2d = np.array([(1,2,3), (4,5,6), (7,8,9)])
print( array_2d )
print( "-----------------------------------------" )

print( "--다차원 배열 선언 + 무작위 값 삽입-------------" )
array_2d_empty = np.empty([3, 3])
print( array_2d_empty )
print( "-----------------------------------------" )
print( "np.zeros() / np.ones()" )
print( "-----------------------------------------" )

print( "--다차원 배열 선언 + 테스트 데이터 생성----------" )
array_arange = np.arange(0, 10, 2, dtype=float)
print( array_arange )
print( "-----------------------------------------" )
print( "np.linspace()" )
print( "-----------------------------------------" )

print( "--넘파이에서 데이터를 정렬하기------------------" )
print( np.sort(array_1d) )
print( "-----------------------------------------" )
print( "-----------------------------------------" )

print( "--넘파이와 넘파이를 결합하기--------------------" )
np_tmp = np.array([3, 8, 10, 5, 9, 99])
np_concat = np.concatenate([array_1d, np_tmp])
print( np_concat )
print( "-----------------------------------------" )
print( "-----------------------------------------" )

print( "--넘파이에서 '99' 값 제거하기------------------" )
np_concat_data_delete = np.delete(np_concat, [-1])
print( np_concat_data_delete )
print( "-----------------------------------------" )
print( "-----------------------------------------" )

--1차원 배열 선언 + 데이터 타입 변경------------
[ 8.  2.  2.  5.  9. 10. 13.  3.]
-----------------------------------------
--2차원 배열 선언 + 데이터 타입 변경------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
-----------------------------------------
--다차원 배열 선언 + 무작위 값 삽입-------------
[[4.67908828e-310 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]
-----------------------------------------
np.zeros() / np.ones()
-----------------------------------------
--다차원 배열 선언 + 테스트 데이터 생성----------
[0. 2. 4. 6. 8.]
-----------------------------------------
np.linspace()
-----------------------------------------
--넘파이에서 데이터를 정렬하기------------------
[ 2.  2.  3.  5.  8.  9. 10. 13.]
-----------------------------------------
-----------------------------------------
--넘파이와 넘파이를 결합하기--------------------
[ 8.  2.  2.  5.  9. 10. 13.  3.  3.  8. 10.  5.  9. 99.]
-----------------------------------------
-----------------------------------------
--

In [2]:
from google.colab import drive
drive.mount('/content/drive')

print( "--넘파이 배열의 차원/크기/모양 확인, 처리하기------" )
print( "--넘파이를 활용하여, 데이터 객체 생성하기---------" )
np_data = np.loadtxt('/content/drive/My Drive/lion/PART12/dataset/wine.csv', delimiter=",", dtype=np.float32)

print( np_data )
print( "-----------------------------------------" )

Mounted at /content/drive
--넘파이 배열의 차원/크기/모양 확인, 처리하기------
--넘파이를 활용하여, 데이터 객체 생성하기---------
[[ 7.  1.  0. ...  9.  5.  1.]
 [ 8.  1.  0. ... 10.  5.  1.]
 [ 8.  1.  0. ... 10.  5.  1.]
 ...
 [ 7.  0.  0. ...  9.  6.  0.]
 [ 6.  0.  0. ... 13.  7.  0.]
 [ 6.  0.  0. ... 12.  6.  0.]]
-----------------------------------------


In [3]:
print( "--넘파이 배열 사이즈 확인, 처리하기--------------" )
print( "총 {} 개".format(np_data.size) )
print( "-----------------------------------------" )
print( "-----------------------------------------" )

print( "--넘파이 배열 사이즈 확인, 처리하기--------------" )
print( "모양".format(np_data.shape) )
print( "{} x {}".format(np_data.shape[0], np_data.shape[1]) )
print( "-----------------------------------------" )
print( "-----------------------------------------" )

print( "--넘파이 배열 형태 변경-----------------------" )
np_concat_data_delete_copy = np.delete(np_concat, [0, 1])
print( np_concat_data_delete_copy )
print( len(np_concat_data_delete_copy) )

np_data_reshape = np_concat_data_delete_copy.reshape(6, 2)
print( np_data_reshape )
print( "-----------------------------------------" )
print( "-----------------------------------------" )

print( "--넘파이 슬라이스 하기------------------------" )
print( np_data_reshape[0] )
print( np_data_reshape[0:2] )
print( np_data_reshape[0:3, 1] )

print( "-----------------------------------------" )
print( "-----------------------------------------" )

--넘파이 배열 사이즈 확인, 처리하기--------------
총 84461 개
-----------------------------------------
-----------------------------------------
--넘파이 배열 사이즈 확인, 처리하기--------------
모양
6497 x 13
-----------------------------------------
-----------------------------------------
--넘파이 배열 형태 변경-----------------------
[ 2.  5.  9. 10. 13.  3.  3.  8. 10.  5.  9. 99.]
12
[[ 2.  5.]
 [ 9. 10.]
 [13.  3.]
 [ 3.  8.]
 [10.  5.]
 [ 9. 99.]]
-----------------------------------------
-----------------------------------------
--넘파이 슬라이스 하기------------------------
[2. 5.]
[[ 2.  5.]
 [ 9. 10.]]
[ 5. 10.  3.]
-----------------------------------------
-----------------------------------------


In [4]:
print( "--넘파이 열 맞춰 배열 쌓기 (세로쌓기)------------" )
np_array_1 = np_data_reshape
np_array_2 = np_data_reshape

np_array_vstack = np.vstack([np_array_1, np_array_2])

print( np_array_vstack )
print( "-----------------------------------------" )
print( "-----------------------------------------" )

print( "--넘파이 열 맞춰 배열 쌓기 (가로쌓기)------------" )
np_array_1 = np_data_reshape
np_array_2 = np_data_reshape

np_array_hstack = np.hstack([np_array_1, np_array_2])

print( np_array_hstack )
print( "-----------------------------------------" )
print( "-----------------------------------------" )

print( "--넘파이 열 맞춰 배열 자르기 (세로쌓기)------------" )
np_array_hsplit = np.hsplit(np_array_hstack, 2)
print( np_array_hsplit )
print( "-----------------------------------------" )
print( "-----------------------------------------" )

--넘파이 열 맞춰 배열 쌓기 (세로쌓기)------------
[[ 2.  5.]
 [ 9. 10.]
 [13.  3.]
 [ 3.  8.]
 [10.  5.]
 [ 9. 99.]
 [ 2.  5.]
 [ 9. 10.]
 [13.  3.]
 [ 3.  8.]
 [10.  5.]
 [ 9. 99.]]
-----------------------------------------
-----------------------------------------
--넘파이 열 맞춰 배열 쌓기 (가로쌓기)------------
[[ 2.  5.  2.  5.]
 [ 9. 10.  9. 10.]
 [13.  3. 13.  3.]
 [ 3.  8.  3.  8.]
 [10.  5. 10.  5.]
 [ 9. 99.  9. 99.]]
-----------------------------------------
-----------------------------------------
--넘파이 열 맞춰 배열 자르기 (세로쌓기)------------
[array([[ 2.,  5.],
       [ 9., 10.],
       [13.,  3.],
       [ 3.,  8.],
       [10.,  5.],
       [ 9., 99.]]), array([[ 2.,  5.],
       [ 9., 10.],
       [13.,  3.],
       [ 3.,  8.],
       [10.,  5.],
       [ 9., 99.]])]
-----------------------------------------
-----------------------------------------


In [5]:
print( "--넘파이 계산/통계 기능 활용하기------------" )

print( np_data_reshape )
print( np_data_reshape.sum() )
print( np_data_reshape.max() )
print( np_data_reshape.min() )
print( np_data_reshape.mean() )
print( np_data_reshape.std() )
print( "-----------------------------------------" )
print( "-----------------------------------------" )

--넘파이 계산/통계 기능 활용하기------------
[[ 2.  5.]
 [ 9. 10.]
 [13.  3.]
 [ 3.  8.]
 [10.  5.]
 [ 9. 99.]]
176.0
99.0
2.0
14.666666666666666
25.636345726765
-----------------------------------------
-----------------------------------------


In [6]:
print( "--넘파이 난수 생성/처리 기능 활용하기------------" )

np_randint = np.random.randint(0, 45, size=6)
print( np_randint ) # 정수형 배열 생성

np_rand = np.random.rand(3, 3)
print( np_rand ) # 0~1 사이의 값으로 3행 3열 배열

np_randn = np.random.randn(4)
print( np_randn ) # 표준 정규 분포를 적용한 형태의 배열

print( np_randint ) # shuffle 전
np.random.shuffle(np_randint)
print( np_randint ) # shuffle 후

np_texts = ['A', 'B', 'C', 'D', 'E']
np_choice = np.random.choice(np_texts, 7, p=[0.1, 0, 0.3, 0.6, 0])
print(np_choice)

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
print( np.unique(np_choice) )

np_test_array = np.array([ ("강남구", "성동구", "도봉구"), ("송파구","영등포구", "관악구"), ("서초구", "중랑구", "마포구") ])
print( np_test_array )
print( np_test_array.T )
print( "-----------------------------------------" )
print( "-----------------------------------------" )

--넘파이 난수 생성/처리 기능 활용하기------------
[27 26 42  0 12 32]
[[0.61932188 0.22833904 0.37572311]
 [0.64279816 0.26367371 0.46979612]
 [0.16252029 0.81703803 0.64160446]]
[ 0.21205662 -0.09762141 -0.84572215 -0.68085354]
[27 26 42  0 12 32]
[ 0 12 42 26 32 27]
['A' 'C' 'D' 'C' 'C' 'D' 'D']
['A' 'C' 'D']
[['강남구' '성동구' '도봉구']
 ['송파구' '영등포구' '관악구']
 ['서초구' '중랑구' '마포구']]
[['강남구' '송파구' '서초구']
 ['성동구' '영등포구' '중랑구']
 ['도봉구' '관악구' '마포구']]
-----------------------------------------
-----------------------------------------
