In [1]:
import numpy as np

In [2]:
# 1행 13열을 1행 1열로 바꿔보겠습니다.
arr = (np.arange(13*2)).reshape([2, 13])

print("Before\n", arr)
print("-----------------------------------------------")

arr[0][12] = arr[0][0]  # 1행 13열이므로 index [0][12]
print("After\n",arr)

Before
 [[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24 25]]
-----------------------------------------------
After
 [[ 0  1  2  3  4  5  6  7  8  9 10 11  0]
 [13 14 15 16 17 18 19 20 21 22 23 24 25]]


In [3]:
# 파일 불러오는 명령어 : loadtxt
wine = np.loadtxt("dataset/wine.csv", delimiter=",")

# 포도주 고정산도 / 휘발성 산도 / 구연산 / 잔류 설탕 / 염화물 / 자유황산 / 총 이산화황 / 밀도 / pH / 황산염 / 알코올 / 품질 = 분류값(종속변수)
# 특정 와인의 모든 속성이 하나로 포함된 행을 가졌습니다.
print(wine)

print("-----------------------------------------------------------------------------")
# 와인을 구분하는 모든 속성들이 속성단위로 묶인 행을 가졌습니다.
print(wine.T)


[[ 7.  1.  0. ...  9.  5.  1.]
 [ 8.  1.  0. ... 10.  5.  1.]
 [ 8.  1.  0. ... 10.  5.  1.]
 ...
 [ 7.  0.  0. ...  9.  6.  0.]
 [ 6.  0.  0. ... 13.  7.  0.]
 [ 6.  0.  0. ... 12.  6.  0.]]
-----------------------------------------------------------------------------
[[ 7.  8.  8. ...  7.  6.  6.]
 [ 1.  1.  1. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 ...
 [ 9. 10. 10. ...  9. 13. 12.]
 [ 5.  5.  5. ...  6.  7.  6.]
 [ 1.  1.  1. ...  0.  0.  0.]]


In [4]:
# LV1 : 데이터셋에 빈 값이 존재합니다. 확률적인 분포(백분율) 을 기반으로 데이터셋을 새롭게 생성하세요!

def menu_pick(RANK, pick):
  menu = np.empty([RANK], dtype=object)
  prob = list(np.random.randn(pick))
  for idx in range(RANK):
    menu[idx] = input(f"{idx+1}번째로 좋아하는 음식은? : ")
  your_pick = np.random.choice(menu, pick, prob)
  return your_pick

print(menu_pick(3, 10))

['공주칼국수' '공주칼국수' '홍두깨칼국수' '홍두깨칼국수' '바지락칼국수' '홍두깨칼국수' '홍두깨칼국수' '홍두깨칼국수'
 '공주칼국수' '공주칼국수']


In [5]:
# LV2 : 로또 번호 생성기

def lotto():
  lotto = np.unique(np.random.randint(1, 46, 7))
  while lotto.size != 7:
    new = np.random.randint(1, 46, 1)
    print(f"\t중복된 값이 있으므로 숫자를 새로 뽑습니다. -> new number : {new}")
    lotto = np.unique(np.concatenate([lotto, new]))
  return lotto

print(f"생성된 로또 번호는 {lotto()} 입니다")

	중복된 값이 있으므로 숫자를 새로 뽑습니다. -> new number : [24]
	중복된 값이 있으므로 숫자를 새로 뽑습니다. -> new number : [44]
생성된 로또 번호는 [ 8 11 16 24 39 44 45] 입니다


In [6]:
# LV3 : 데이터셋의 정보를 손쉽게 찾아주는 메소드를 제작합니다.

def info_finder(path):
  data = np.loadtxt(path, delimiter=",")

  # 요약
  # 차이값 : 표준편차
  print(f"""
  전체 데이터 Description
  생성한 배열 : {len(data.shape)}차원
  생성한 배열 원소 : {data.size}개
  생성한 배열 높은 값 : {data.max()}
  생성한 배열 낮은 값 : {data.min()}
  생성한 배열 평균 값 : {data.mean()}
  생선한 배열 차이 값 : {data.std()}
  """)

  while int(input("특정값까지의 데이터 분석 (1) / 함수 종료 (2) : ")) == 1:
    VAL = int(input("Integer Values : "))
    print(f"""
    특정 범위 배열 높은 값 : {data[:VAL].max()}
    특정 범위 배열 낮은 값 : {data[:VAL].min()}
    특정 범위 배열 평균 값 : {data[:VAL].mean()}
    특정 범위 배열 차이 값 : {data[:VAL].std()}
    """)

  print("함수 종료")
  
info_finder("./dataset/wine.csv")

# 전체 데이터 Description
# 생성한 배열 : 2차원
# 생성한 배열 원소 : 84461개
# 생성된 배열 높은 값 : 440.0
# 생성된 배열 낮은 값 : 0.0
# 생성된 배열 평균 값 : 13.882288932800293
# 생성된 배열 차이 값 : 34.641963958740234
# 특정값까지의 데이터 분석 (1) / 함수 종료 (2) : 1
# Integer Values : 100
# 특정 범위 배열 높은 값 : 148.0
# 특정 범위 배열 낮은 값 : 0.0
# 특정 범위 배열 평균 값 : 8.0369234085083
# 특정 범위 배열 차이 값 : 18.17797088623047
# 특정값까지의 데이터 분석 (1) / 함수 종료 (2) : 300
# 함수 종료


  전체 데이터 Description
  생성한 배열 : 2차원
  생성한 배열 원소 : 84461개
  생성한 배열 높은 값 : 440.0
  생성한 배열 낮은 값 : 0.0
  생성한 배열 평균 값 : 13.882288867051065
  생선한 배열 차이 값 : 34.64078095386516
  

    특정 범위 배열 높은 값 : 148.0
    특정 범위 배열 낮은 값 : 0.0
    특정 범위 배열 평균 값 : 8.036923076923078
    특정 범위 배열 차이 값 : 18.17797119280341
    
함수 종료
